Move to a bare shell script
There is no `zenity` in Fedora Silverblue (which the actual user of this
script uses) so move to a bare shell script instead.

This is also only tested on Fedora Silverblue.

diff --git a/image-convert b/image-convert
--- a/image-convert
+++ b/image-convert
@@ -2,200 +2,229 @@
 # SPDX-License-Identifier: GPL-3.0-only
 # Copyright 2022, Mattias Bengtsson <mattias.jc.bengtsson@gmail.com>
 
-set -e
-set -o pipefail
+# Dynamic dispatch in the task function.
+# shellcheck disable=SC2329
 
-NAUTILUS_SCRIPTS="${XDG_DATA_HOME:-$HOME/.local/share}/nautilus/scripts/"
+set -euo pipefail
+
+NAUTILUS_SCRIPTS="${XDG_DATA_HOME:-${HOME}/.local/share}/nautilus/scripts/"
 
 NAUTILUS_SCRIPT="${NAUTILUS_SCRIPTS}/.image-convert"
 NAUTILUS_SCRIPT_SYMLINKS=( "Image - Add Border" )
 
 ################################################################################
 
-function graphical {
+# shellcheck disable=SC2329
+function debug {
+    if [ -v DEBUG ]; then
+        echo "${FUNCNAME[1]:+${FUNCNAME[1]}: }${*}" >/dev/stderr
+    fi
+}
+
+function nautilus-script {
     test -v NAUTILUS_SCRIPT_CURRENT_URI || test -v FORCE_GRAPHICAL
 }
 
-function error {
-    local title text
+function anykey {
+    local verb
 
-    title="${1}"
-    shift
-    text="${*}"
+    verb="${1:-exit}"
 
-    if graphical; then
-        zenity --error --text "${text}" --title "${title}"
-    else
-        echo "${*}" > /dev/stderr
-    fi
-}
-
-function info {
-    local title text
-
-    title="${1}"
-    shift
-    text="${*}"
-
-    if graphical; then
-        zenity --info --title "${title}" --text "${text}"
-    else
-        echo -ne "${title} "
-        read -n 1 -s -r -p "${*}"
-        echo
-    fi
+    echo
+    read -n 1 -srp "Press any key to ${verb}."
+    echo
+    echo
 }
 
 function confirm {
-    local title text
+    local default
 
-    title="${1}"
+    default="${1}"
+
+    case "${default}" in
+        y) read -p "${*:2} [Y/n] " -n 1 -r -s ;;
+        n) read -p "${*:2} [N/y] " -n 1 -r -s ;;
+        *) echo "Unknown default value: '${default}'" >&2
+           return 2
+           ;;
+    esac
+
+    echo
+    [[ ${REPLY:-${default}} =~ ^[Yy]$ ]]
+}
+
+# Print [n/m] with proper alignment
+#  n-of-m 1 10    ⇒  [01/10]
+#  n-of-m 10 200  ⇒  [010/200]
+function n-of-m {
+    local n m fmt
+
+    n="${1}"
+    m="${2}"
+    fmt="%0${#m}d"
+
+    # shellcheck disable=SC2059
+    printf "[${fmt}/${fmt}]" "${n}" "${m}"
+}
+
+function color {
+    local color
+
+    color="${1}"
+
+    case "${color}" in
+        b|black)   tput setaf 0 ;;
+        r|red)     tput setaf 1 ;;
+        g|green)   tput setaf 2 ;;
+        y|yellow)  tput setaf 3 ;;
+        u|blue)    tput setaf 4 ;;
+        m|magenta) tput setaf 5 ;;
+        c|cyan)    tput setaf 6 ;;
+        w|white)   tput setaf 7 ;;
+        *)         echo "ERROR: No such color ${color}!" >&2
+                   return 2     ;;
+    esac
     shift
-    text="${*}"
 
-    if graphical; then
-        zenity --question --title="${title}" --text "${text}"
-        return $?
+    echo "${@}"
+
+    tput sgr0
+}
+function task {
+    local msg out
+    local -a cmd
+
+    msg="${1}"
+    cmd=("${@:2}")
+
+    printf "%-30s" "${msg} ... "
+
+    if out="$("${cmd[@]}" 2>&1)"; then
+        echo -e "[ $(color g -n ✓) ]"
     else
-        read -p "${title}: ${text} [Y/n] " -n 1 -r -s
-        echo
-        [[ ! ${REPLY} =~ ^[Nn]$ ]]
+        echo -e "[ $(color r -n ×) ]"
+        echo "${out}" | pr -to 6 >&2
+        return 1
     fi
 }
 
-function read-password {
-    zenity --title="Password" --password
+function isnum {
+    case "${*}" in
+        ''|*[!0-9]*)
+            return 1
+            ;;
+        *)  ;;
+    esac
+}
+
+function info {
+    echo -e "${*}"
+
+    anykey continue
+}
+
+function error {
+    local title
+    local -a body
+
+    title="${1}"
+    body=( "${@:2}" )
+
+    echo "Error: ${title}" >&2
+
+    if [ "${#body[@]}" -gt 0 ]; then
+        echo
+        for msg in "${body[@]}"; do
+            echo "${msg}" >&2
+        done
+    fi
+
+    exit 2
 }
 
 function output-dir {
     if [ -e ./out ]; then
-        error "Output directory exists!"                                       \
-              "Remove the [out/] directory before continuing!"
-        exit 2
+        error "Output directory exists!" \
+              "Remove the [out/] directory before trying again!"
     fi
 
     command install -d out
 }
 
-function authenticate {
-    local result ps
+################################################################################
 
-    # Just return if we already have a sudo ticket
-    if sudo -vn &> /dev/null; then
-        return
+function get-border-width {
+    read -p "Border width in pixels: " -r -i 5
+    echo
+
+    if ! isnum "${REPLY}"; then
+        error "Not a number: '${REPLY}'"
     fi
 
-    read-password | sudo -Sv 2>/dev/null
-    # Only way I've found to capture both PIPESTATUS[0] *and* $? at the same
-    # time. Don't touc this!
-    result=$? ps=${PIPESTATUS[0]}
-
-    if (( ps > 0 )); then
-        echo exit
-        return
-    fi
-
-    return $result
+    echo "${REPLY}"
 }
 
-function gsudo {
-    local title
+function get-border-color {
+    echo "#000000"
+}
 
-    title="Password"
+function add-border {
+    local image
 
-    for i in {1..3}; do
-        if authenticate "${title}"; then
-            sudo -n "${@}"
-            return $?
-        else
-            title="Password — Try again!"
-        fi
+    image="${1:-}"
+
+    if [ ! -f "${image}" ]; then
+        error "Not an image: '${image}'!"
+    fi
+
+    image="$(basename "${image}")"
+
+    convert -bordercolor "${color}" -border "${width}" "${image}"              \
+            -quality '100%' "out/${image}"
+}
+
+function add-border-main {
+    local width color image i tot fmt
+    local -a images
+
+    output-dir
+    echo
+
+    width="$(get-border-width)"
+    color="$(get-border-color)"
+    images=( "${@}" )
+
+    echo
+
+    i=0
+    tot="${#images[@]}"
+    for image in "${images[@]}"; do
+        : "$((i++))"
+        task "$(n-of-m "${i}" "${tot}") ${image}" add-border "${image}"
     done
 }
 
 ################################################################################
 
-function get-border-width {
-    zenity --scale                                                             \
-           --min-value=1                                                       \
-           --max-value=50                                                      \
-           --value=5                                                           \
-           --text="Border Width"
-}
-
-function get-border-color {
-    zenity --color-selection --color=\#000000
-}
-
-function add-border {
-    local width color i num_images
-
-    width="$(get-border-width)"
-    color="$(get-border-color)"
-    i=0
-    images=( "${@}" )
-    num_images="${#images[@]}"
-
-    output-dir
-
-    ( for image in "${images[@]}"; do
-          image="$(basename "${image}")"
-          echo "# Adding border to: ${image} ..."
-          convert -bordercolor "${color}" -border "${width}" "${image}"        \
-                  -quality '100%' "out/${image}"
-          (( i=i + 1 ))
-          echo $(( (i * 100) / num_images ))
-      done
-      echo "# Done!"
-    ) | zenity --progress                                                      \
-               --title="Adding border to images"                               \
-               --percentage=0                                                  \
-               --width=420                                                     \
-               --height=100
-}
-
-################################################################################
-
-function install-dependencies {
-    local msg
-
-    msg="Install ImageMagick? [sudo apt install imagemagick]"
-
-    if ! confirm "installer" "${msg}" ; then
-        error "Can't continue!" \
-              "ImageMagick is a necessary dependency for this script!"
-        exit 2
-    fi
-
-    if graphical; then
-        gsudo apt install --yes imagemagick                                    \
-            | tee                                                              \
-            | zenity --title "Installing ImageMagick "                         \
-                     --progress                                                \
-                     --pulsate
+function install-main {
+    if [ ! -e "${NAUTILUS_SCRIPT}" ]; then
+        if confirm y "Do you want to install image-convert?"; then
+            echo
+            task "  Installing image-convert" do-install
+        fi
     else
-        sudo apt install --yes imagemagick
+        echo "image-convert is already installed."
+        echo
+        if confirm y "Do you want to *uninstall* instead?"; then
+            echo
+            task "  Uninstall image-convert" do-uninstall
+        fi
     fi
+
+    exit
 }
 
 function do-install {
-    if [ -e "${NAUTILUS_SCRIPT}" ]; then
-        if confirm "Installer"                                                 \
-                   "image-convert is already installed.\n\n"                   \
-                   "Do you want to uninstall image-convert?"; then
-            do-uninstall
-        fi
-        exit
-    fi
-
-    if ! confirm "Installer" "Do you want to install image-convert?"; then
-        exit
-    fi
-
-    if ! command -v convert >/dev/null ; then
-        install-dependencies
-    fi
-
     command install -DT "${0}" "${NAUTILUS_SCRIPT}"
 
     pushd "${NAUTILUS_SCRIPTS}" >/dev/null
@@ -203,15 +232,11 @@ function do-install {
         ln -s ./.image-convert "${symlink}"
     done
     popd >/dev/null
-
-    info "Installation successful!" \
-         "image-convert is now installed!"
 }
 
 function do-uninstall {
     if [ ! -e "${NAUTILUS_SCRIPT}" ]; then
         error "Nothing to do!" "Not installed!"
-        exit
     fi
 
     rm "${NAUTILUS_SCRIPT}"
@@ -221,19 +246,28 @@ function do-uninstall {
         rm "${symlink}"
     done
     popd >/dev/null
-
-    info "Uninstall successful!" \
-         "image-convert is now removed from your computer!"
 }
 
 ################################################################################
 
-case "$(basename "${0}")" in
-    "Image - Add Border")
-        add-border "${@}"
-        ;;
-    image-convert-installer)
-        export FORCE_GRAPHICAL=true
-        do-install
-        ;;
-esac
+function main {
+    local cmd
+
+    if [ ! -t 0 ]; then
+        exec ptyxis --new-window -x "'${0}'$(printf " '%s'" "${@}")"
+    fi
+
+    trap anykey EXIT
+
+    cmd="$(basename "${0}")"
+
+    case "${cmd}" in
+        "Image - Add Border")    add-border-main "${@}"                       ;;
+        image-convert-installer) install-main                                 ;;
+        *) error "Internal error!" \
+                 "The cmd variable had an unexpected value: '${cmd}'!"
+           ;;
+    esac
+}
+
+main "${@}"; exit
